name: talenta_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  carousel_slider: 4.2.1
  hexcolor: 3.0.1
  google_fonts: 6.1.0
  intl: any
  flutter_map_location_marker: ^8.0.8
  month_year_picker: ^0.3.0+1
  camera: 0.10.5+9
  file_picker: 6.2.0
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

